'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('Filme',
    [{
        titulo: 'Mulher Maravilha, 1984',
        tituloOriginal: 'Wonder Woman 1984',
        lancamento: '2020-12-24',
        paisOrigem: 'EUA',
        duracao: '02:31:00',
        sinopse: 'Mulher-Maravilha 1984 acompanha Diana Prince/Mulher-Maravilha (Gal Gadot) em 1984, durante a Guerra Fria, entrando em conflito com dois grande inimigos - o empresário de mídia Maxwell Lord (Pedro Pascal) e a amiga que virou inimiga Barbara Minerva/Cheetah (Kristen Wiig) - enquanto se reúne com seu interesse amoroso Steve Trevor (Chris Pine).',
        rate: 0,
        exibicaoInicio: '2020-12-24',
        exibicaoFinal: '2022-01-07',
        idioma_id: 2,
        genero_id: 2,
        poster_url: './img/posters/mulher-maravilha-1984-poster-desktop.jpg',
        trailer_url: 'XqcsS1azJ_g',
        classificacao: 14,
      },
      {
        titulo: 'Um tio quase perfeito 2',
        tituloOriginal: 'Um tio quase perfeito 2',
        lancamento: '2021-01-07',
        paisOrigem: 'Brasil',
        duracao: '01:42:00',
        sinopse: 'Em Um Tio Quase Perfeito 2, longe da vida de trambiques e vivendo em harmonia com sua família, Tony (Marcus Majella) reina soberano no coração de seus sobrinhos. Porém, quando sua irmã começa a namorar Beto (Danton Mello), um homem aparentemente exemplar, ele corre o risco de perder a atenção dos pequenos. Determinado a acabar com a "concorrência", Tony vai fazer de tudo para que Beto não entre oficialmente para a família.',
        rate: 0,
        exibicaoInicio: '2021-01-07',
        exibicaoFinal: '2022-01-07',
        idioma_id: 1,
        genero_id: 5,
        poster_url: './img/posters/um-tio-quase-perfeito-2-poster-desktop.jpg',
        trailer_url: 'h_C6gFElZ9w',
        classificacao: 0,
      },
      {
        titulo: 'O tempo com você',
        tituloOriginal: 'O tempo com você',
        lancamento: '2021-02-07',
        paisOrigem: 'Brasil',
        duracao: '01:52:00',
        sinopse: 'Durante o verão, Hodaka (Kotaro Daigo) foge de sua casa em uma ilha periférica para chegar a Tóquio. Ele não tem dinheiro mas, depois de muitos dias, acaba encontrando trabalho como escritor freelance para uma revista duvidosa. Um dia, porém, Hodaka conhece uma garota no meio da agitação da cidade grande. Hina (Nana Mori) é uma garota alegre que vive sozinha com seu irmão mais novo, devido a uma série de circunstâncias.',
        rate: 0,
        exibicaoInicio: '2021-02-07',
        exibicaoFinal: '2022-02-07',
        idioma_id: 2,
        genero_id: 5,
        poster_url: './img/posters/o-tempo-com-voce-poster-desktop.jpg',
        trailer_url: 'bFT34NnzPvM',
        classificacao: 12,
      },
      {
        titulo: 'Trolls 2',
        tituloOriginal: 'Trolls 2',
        lancamento: '2020-10-08',
        paisOrigem: 'EUA',
        duracao: '01:30:00',
        sinopse: 'Em Trolls 2, a rainha Poppy (Anna Kendrick) e Branch (Justin Timberlake) fazem uma descoberta surpreendente: há outros mundos Troll além do seu, e suas diferenças criam grandes confrontos entre essas diversas tribos. Quando uma ameaça misteriosa coloca todos os Trolls do país em perigo, Poppy, Branch e seu grupo de amigos devem embarcar em uma jornada épica para criar harmonia entre os Trolls rivais e uní-los contra um mal maior.',
        rate: 0,
        exibicaoInicio: '2020-10-08',
        exibicaoFinal: '2021-10-08',
        idioma_id: 1,
        genero_id: 2,
        poster_url: './img/posters/trolls-2-poster-desktop.jpg',
        trailer_url: 'gaNXC9VAtSc',
        classificacao: 0,
      }
    ], {}),

  down: (queryInterface) => queryInterface.bulkDelete('Filme', null, {}),
};